CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE urls
ADD COLUMN user_id INT;

ALTER TABLE urls
ADD CONSTRAINT fk_urls_foreign_key
FOREIGN KEY (user_id)
REFERENCES URLS(id);